-- https://school.programmers.co.kr/learn/courses/30/lessons/131123

SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO AS T1 
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVOR FROM REST_INFO GROUP BY FOOD_TYPE) AS T2 
ON T1.FOOD_TYPE=T2.FOOD_TYPE AND T1.FAVORITES=T2.MAX_FAVOR
ORDER BY T1.FOOD_TYPE DESC