-- https://school.programmers.co.kr/learn/courses/30/lessons/59413

SELECT T1.N AS HOUR, IFNULL(T2.COUNT, 0) AS COUNT
FROM (WITH RECURSIVE cte AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 23
    )
SELECT n FROM cte ) AS T1
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)) AS T2
ON T1.N=T2.HOUR