# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"%\n\x0b\x43\x61lcRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1a\n\x0c\x43\x61lcResponse\x12\n\n\x02n1\x18\x01 \x01(\x05\"\x19\n\x0b\x44ivResponse\x12\n\n\x02\x66\x31\x18\x01 \x01(\x02\x32\xd8\x01\n\nCalculator\x12.\n\x03\x41\x64\x64\x12\x11.calc.CalcRequest\x1a\x12.calc.CalcResponse\"\x00\x12\x33\n\x08Subtract\x12\x11.calc.CalcRequest\x1a\x12.calc.CalcResponse\"\x00\x12\x33\n\x08Multiply\x12\x11.calc.CalcRequest\x1a\x12.calc.CalcResponse\"\x00\x12\x30\n\x06\x44ivide\x12\x11.calc.CalcRequest\x1a\x11.calc.DivResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CALCREQUEST']._serialized_start=20
  _globals['_CALCREQUEST']._serialized_end=57
  _globals['_CALCRESPONSE']._serialized_start=59
  _globals['_CALCRESPONSE']._serialized_end=85
  _globals['_DIVRESPONSE']._serialized_start=87
  _globals['_DIVRESPONSE']._serialized_end=112
  _globals['_CALCULATOR']._serialized_start=115
  _globals['_CALCULATOR']._serialized_end=331
# @@protoc_insertion_point(module_scope)
